# Generated by Django 5.2 on 2025-04-25 21:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='PerfilAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='perfil_alunos/', verbose_name='Imagem de Perfil')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografia')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='inscricoes.aluno')),
            ],
            options={
                'verbose_name': 'Perfil do Aluno',
                'verbose_name_plural': 'Perfis dos Alunos',
            },
        ),
    ]
