# Generated by Django 5.2 on 2025-04-28 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bi_pdf', models.FileField(upload_to='inscricoes/bi/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('nome_completo', models.CharField(max_length=200)),
                ('numero_bi', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('idade', models.PositiveIntegerField()),
                ('data_emissao_bi', models.DateField()),
                ('genero', models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino')], max_length=10)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('certificado_9classe', models.FileField(upload_to='inscricoes/certificados/')),
                ('atestado_medico', models.FileField(blank=True, null=True, upload_to='inscricoes/atestados/')),
                ('curso', models.CharField(choices=[('electrotecnica', 'Electrotécnica'), ('mecanica', 'Mecânica Industrial'), ('informatica', 'Informática Industrial')], max_length=50)),
                ('escola_anterior', models.CharField(max_length=200)),
                ('ano_conclusao', models.PositiveIntegerField()),
                ('endereco_escola', models.TextField(blank=True)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('provincia', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('endereco', models.TextField()),
                ('motivacao', models.TextField()),
                ('expectativas', models.TextField()),
                ('planos_futuros', models.TextField()),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('aceitou_termos', models.BooleanField(default=False)),
                ('receber_info', models.BooleanField(default=False)),
                ('bi_valido', models.BooleanField(default=False)),
                ('dados_extraidos', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
    ]
