# Generated by Django 5.2 on 2025-04-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_inscricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscricao',
            old_name='data_emissao_bi',
            new_name='data_emissao',
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
