# Generated by Django 5.2 on 2025-04-28 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0003_rename_data_emissao_bi_inscricao_data_emissao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Envio')),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado')),
                ('alunos_enviados', models.ManyToManyField(blank=True, related_name='envios', to='inscricoes.aluno')),
            ],
            options={
                'verbose_name': 'Envio de Mensagem',
                'verbose_name_plural': 'Envios de Mensagens',
            },
        ),
    ]
