# Generated by Django 5.2 on 2025-04-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0004_enviomensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviomensagem',
            name='progresso',
            field=models.IntegerField(default=0, verbose_name='Progresso'),
        ),
        migrations.AddField(
            model_name='enviomensagem',
            name='total_alunos',
            field=models.IntegerField(default=0, verbose_name='Total de Alunos'),
        ),
        migrations.AlterField(
            model_name='enviomensagem',
            name='mensagem',
            field=models.TextField(verbose_name='Mensagem'),
        ),
    ]
