# Generated by Django 5.2 on 2025-04-29 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0005_enviomensagem_progresso_enviomensagem_total_alunos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'ordering': ['-data_inscricao'], 'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='aceitou_termos',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='bi_pdf',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='bi_valido',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='certificado_9classe',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='dados_extraidos',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='receber_info',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='aceita_termos',
            field=models.BooleanField(default=1, verbose_name='Aceita os Termos e Condições'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao',
            name='certificado',
            field=models.FileField(default=1, upload_to='documentos/certificados/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Certificado da 9ª Classe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao',
            name='copia_bi',
            field=models.FileField(default=1, upload_to='documentos/bi/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Cópia do BI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='receber_informacoes',
            field=models.BooleanField(default=False, verbose_name='Deseja receber informações'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='ano_conclusao',
            field=models.PositiveIntegerField(verbose_name='Ano de Conclusão'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='atestado_medico',
            field=models.FileField(default=1, upload_to='documentos/atestados/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Atestado Médico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='curso',
            field=models.CharField(choices=[('electrotecnica', 'Electrotécnica'), ('mecanica', 'Mecânica Industrial'), ('informatica', 'Informática Industrial')], max_length=50, verbose_name='Curso Selecionado'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='data_emissao',
            field=models.DateField(verbose_name='Data de Emissão do BI'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='data_inscricao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='endereco',
            field=models.CharField(max_length=300, verbose_name='Endereço Completo'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='endereco_escola',
            field=models.CharField(max_length=300, verbose_name='Endereço da Escola'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='escola_anterior',
            field=models.CharField(max_length=200, verbose_name='Escola Anterior'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='expectativas',
            field=models.TextField(verbose_name='Expectativas em relação ao Curso'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=10, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='idade',
            field=models.PositiveIntegerField(default=1, verbose_name='Idade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='motivacao',
            field=models.TextField(verbose_name='Motivação para o Curso'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='municipio',
            field=models.CharField(max_length=50, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='nacionalidade',
            field=models.CharField(max_length=100, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='nome_completo',
            field=models.CharField(max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='numero_bi',
            field=models.CharField(max_length=14, verbose_name='Número do BI'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='planos_futuros',
            field=models.TextField(verbose_name='Planos Futuros'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='provincia',
            field=models.CharField(max_length=50, verbose_name='Província'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
