# Generated by Django 5.2 on 2025-04-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0006_alter_inscricao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Curso')),
                ('descricao', models.TextField(verbose_name='Descrição do Curso')),
                ('duracao', models.CharField(max_length=50, verbose_name='Duração')),
                ('imagem', models.ImageField(upload_to='cursos/', verbose_name='Imagem do Curso')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque (Novo/Popular)')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
