# Generated by Django 5.2 on 2025-04-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0007_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Evento')),
                ('descricao', models.TextField(verbose_name='Descrição do Evento')),
                ('data', models.DateField(verbose_name='Data do Evento')),
                ('horario_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('horario_fim', models.TimeField(verbose_name='Hora de Fim')),
                ('local', models.CharField(max_length=255, verbose_name='Local do Evento')),
                ('imagem', models.ImageField(upload_to='eventos/', verbose_name='Imagem do Evento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
