# Generated by Django 5.2 on 2025-05-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0010_alunoa_alter_inscricao_numero_bi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlunoA',
        ),
    ]
