# Generated by Django 5.2.1 on 2025-05-10 17:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0013_area_curso_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Área de Pesquisa',
                'verbose_name_plural': 'Áreas de Pesquisa',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('icone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('atual', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Experiência Profissional',
                'verbose_name_plural': 'Experiências Profissionais',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='FormacaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau', models.CharField(choices=[('GR', 'Graduação'), ('ES', 'Especialização'), ('ME', 'Mestrado'), ('DO', 'Doutorado'), ('PD', 'Pós-Doutorado')], max_length=2)),
                ('curso', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=100)),
                ('ano_conclusao', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Formação Acadêmica',
                'verbose_name_plural': 'Formações Acadêmicas',
                'ordering': ['-ano_conclusao', 'grau'],
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('AR', 'Artigo'), ('LI', 'Livro'), ('CP', 'Capítulo de Livro'), ('TR', 'Trabalho em Conferência'), ('OU', 'Outro')], max_length=2)),
                ('autores', models.CharField(max_length=300)),
                ('veiculo', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('link', models.URLField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'ordering': ['-ano', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.departamento')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
                'unique_together': {('nome', 'departamento')},
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='docentes/')),
                ('cargo', models.CharField(choices=[('PR', 'Professor'), ('CO', 'Coordenador'), ('DC', 'Diretor de Curso'), ('DP', 'Diretor de Departamento')], default='PR', max_length=2)),
                ('nivel', models.CharField(choices=[('AS', 'Assistente'), ('AD', 'Adjunto'), ('TI', 'Titular'), ('VI', 'Visitante')], default='AS', max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('lattes', models.URLField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('horario_atendimento', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('areas_pesquisa', models.ManyToManyField(blank=True, to='inscricoes.areapesquisa')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.departamento')),
                ('disciplinas', models.ManyToManyField(blank=True, to='inscricoes.disciplina')),
                ('experiencia', models.ManyToManyField(blank=True, to='inscricoes.experienciaprofissional')),
                ('formacao', models.ManyToManyField(blank=True, to='inscricoes.formacaoacademica')),
                ('publicacoes', models.ManyToManyField(blank=True, to='inscricoes.publicacao')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['nome'],
            },
        ),
    ]
