# Generated by Django 5.2.1 on 2025-05-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0014_areapesquisa_departamento_experienciaprofissional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
